version: '3'
services:
  # Постгрес база в отдельном контейнере
  postgres:
    # Устанавливаем готовый образ
    image: postgres
    # Задаем глобальные переменные для доступа к PG
    environment:
      - POSTGRES_PASSWORD=ghwf94hfw8
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
    restart: always
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Airflow в отдельном контейнере
  airflow:
    # Сборка из Dockerfile
    build:
      context: .
      args:
        FERNET_KEY: "7INtZwHO0qtO9QbB-P9On407hvHS-Q2QOupz7ak-TuU="
    restart: always
    # Определяет порядок запуска сервисов
    # Будем ждать postgres
    depends_on:
      - postgres
    # Пробрасываем порты
    ports:
      - 8001:8080
    # Пробрасываем папку с дагами
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/root/airflow/plugins
      - logs:/usr/local/airflow/logs
  # Добавляем сервис Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080  # Пробрасываем порт 8081 на хост для доступа к Adminer
    depends_on:
      - postgres  # Зависимость от сервиса postgres
# Задав таким образом вольюмы
# нам не нужно заботиться о том где будет папка
# В которой они будут лежать
# Для баз данных и логов такой способ более простой и безопасный
volumes:
  pgdata:
  logs:
